### ISSUE TITLE
Random or Chunked Reading

### ISSUE THREAD

**Issue by quasiben** [chatnoir-eu/chatnoir-resiliparse#29]
Thanks for developing fastwarc!  It's been a great tool while I've been exploring text extracting of common crawl with Python.  

I'm interested in using it as part of much larger pipeline but want to enable chunked processing and I'm curious if this is possible.   My understanding at the moment is that the `ArchiverIterator` gives me a nice handle to process the all `WarcRecords` sequentially.  I think I'd like to be able to do is something like:

```python
archv = ArchiveChunked(open(...), ...)
recs = archv[N:N+10] # select 10 records starting at N
```

Doing this should allow me to leverage batch processing functionality and distributed the processing across multiple cores

**Comment by phoerious** [comment]
Hi, sorry for the delayed response.

Random access to WARC records requires either a linear read or an index of the record start offsets. The former can be emulated by simply skipping the first n entries, the latter requires a different WARC format. The latter might be possible in the future with zstandard instead of GZip: https://iipc.github.io/warc-specifications/specifications/warc-zstd/

**Comment by quasiben** [comment]
Thanks @phoerious !

Do you know how I would supply a record start offsets to the ArchiveIterator or would this essentially be call next()/iterating without parsing N times the consuming the WarcRecord ?

**Comment by phoerious** [comment]
If you know the offset, you can simply seek to the position before starting the ArchiveIterator. Otherwise, you need to call next() or continue in a loop a bunch of times.
